# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import nilai_import.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import_Nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=5)),
                ('bulan', models.CharField(max_length=10)),
                ('nilai', models.FloatField()),
                ('berat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='regresi_korelasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=5)),
                ('hasil_regresi', models.FloatField()),
                ('hasil_korelasi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='table_post_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('document', models.FileField(upload_to='documents/', validators=[nilai_import.validator.validate_file_extension])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='regresi_korelasi',
            name='post_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nilai_import.table_post_description'),
        ),
        migrations.AddField(
            model_name='import_nilai',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nilai_import.table_post_description'),
        ),
    ]
